core_type: sparc
config_name: sparc_2x2
x_tiles: 2
y_tiles: 2
total_tiles: 4
simulator: vlt
generation_date: Wed Aug 12 11:02:44 PM CST 2026
rtl_only: true
description: "OpenPiton sparc configuration with 2x2 tiles"
