core_type: sparc
config_name: sparc_1x4
x_tiles: 1
y_tiles: 4
total_tiles: 4
simulator: vlt
generation_date: Wed Aug 12 11:04:00 PM CST 2026
rtl_only: true
description: "OpenPiton sparc configuration with 1x4 tiles"
