project: pulp_cluster
config_name: pulp_cluster_snapshot
generation_date_utc: 2026-04-15 15:46:09
git_commit_short: caaa9735
source_snapshot: /home/yongfu/proj/score/datasets/pulp_cluster/caaa9735/source_snapshot
