project: rv_tracer
config_name: rv_tracer_snapshot
generation_date_utc: 2026-08-10 18:05:54
git_commit_short: b7e65fd7
source_snapshot: /home/yongfu/proj/score/datasets/rv_tracer/b7e65fd7/source_snapshot
