# Generated by scripts/install_opentitan.sh — SCORE OpenTitan environment
# shellcheck shell=bash
_OT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_OT_HOST="$(cd "$_OT_ROOT/../opentitan-host-tools" && pwd)"
if [[ -f "$_OT_ROOT/.venv/bin/activate" ]]; then
    # shellcheck source=/dev/null
    source "$_OT_ROOT/.venv/bin/activate"
fi
# Prefer /tools/verilator/v4.210 — lowRISC prebuilts bake that prefix into makefiles.
export PATH="/tools/verilator/v4.210/bin:$_OT_ROOT/.venv/bin:$_OT_HOST/verilator/v4.210/bin:$_OT_HOST/verible/bin:$_OT_HOST/riscv/bin:$_OT_HOST/srecord/bin:${PATH}"
if [[ -d /tools/verilator/v4.210/share/verilator ]]; then
    export VERILATOR_ROOT="/tools/verilator/v4.210/share/verilator"
elif [[ -d "$_OT_HOST/verilator/v4.210/share/verilator" ]]; then
    export VERILATOR_ROOT="$_OT_HOST/verilator/v4.210/share/verilator"
fi
export RISCV="$_OT_HOST/riscv"
export REPO_TOP="$_OT_ROOT"
unset _OT_ROOT _OT_HOST
