#!/bin/bash
# NEORV32 environment — source from the SCORE repo root: source scripts/neorv32_env.sh
# Generated by install_neorv32_vhdl.sh / install_neorv32_verilog.sh; adds project-local GHDL / Icarus to PATH.

_ENV_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$_ENV_SCRIPT_DIR")"
TOOLS_DIR="$PROJECT_ROOT/tools"

# When sourced from scripts with `set -o pipefail` (e.g. run_neorv32_*.sh), `cmd | head`
# can yield SIGPIPE / non-zero pipeline status and abort the caller under `set -e`.
_first_line() {
    local _out
    _out="$("$@" 2>/dev/null)" || true
    printf '%s\n' "${_out%%$'\n'*}"
}

echo "Setting up NEORV32 environment (PATH)..."

# Add GHDL to PATH (prioritize custom installation over system)
if [[ -d "$TOOLS_DIR/ghdl-install/bin" ]]; then
    export PATH="$TOOLS_DIR/ghdl-install/bin:$PATH"
    echo "✅ Custom GHDL added to PATH (takes priority over system GHDL)"
elif command -v ghdl >/dev/null 2>&1; then
    echo "⚠️  Using system GHDL (may not support synthesis)"
else
    echo "❌ GHDL not found"
fi

# Add Icarus Verilog to PATH
if [[ -d "$TOOLS_DIR/iverilog-install/bin" ]]; then
    export PATH="$TOOLS_DIR/iverilog-install/bin:$PATH"
    echo "✅ Custom Icarus Verilog added to PATH"
elif command -v iverilog >/dev/null 2>&1; then
    echo "✅ Using system Icarus Verilog"
else
    echo "❌ Icarus Verilog not found"
fi

# Add Verilator to PATH
if [[ -d "$TOOLS_DIR/verilator-install/bin" ]]; then
    export PATH="$TOOLS_DIR/verilator-install/bin:$PATH"
    echo "✅ Verilator added to PATH"
fi

# Verify tools and their capabilities
echo ""
echo "=== Tool Verification ==="
if command -v ghdl >/dev/null 2>&1; then
    _ghdl_version=$(_first_line ghdl --version)
    _ghdl_path=$(command -v ghdl)
    echo "GHDL: $_ghdl_version"
    echo "  Location: $_ghdl_path"

    if grep -q "synth" <<<"$(ghdl --help 2>/dev/null || true)"; then
        echo "  ✅ Synthesis support: Available"
        if ghdl help synth >/dev/null 2>&1; then
            echo "  ✅ Synthesis command: Working"
        else
            echo "  ⚠️  Synthesis command: May have issues"
        fi
    else
        echo "  ❌ Synthesis support: Not available"
        echo "  💡 This GHDL version cannot convert VHDL to Verilog"
    fi
else
    echo "GHDL: Not found"
fi

if command -v iverilog >/dev/null 2>&1; then
    _iverilog_version=$(_first_line iverilog -V)
    echo "Icarus Verilog: $_iverilog_version"
else
    echo "Icarus Verilog: Not found"
fi

if command -v verilator >/dev/null 2>&1; then
    _verilator_version=$(_first_line verilator --version)
    echo "Verilator: $_verilator_version"
else
    echo "Verilator: Not installed (optional)"
fi

echo ""
if command -v ghdl >/dev/null 2>&1 && grep -q "synth" <<<"$(ghdl --help 2>/dev/null || true)"; then
    echo "🎉 NEORV32 environment ready (GHDL synthesis)."
    echo "Examples: ./scripts/run_neorv32_verilog.sh  or  ./scripts/generate_neorv32_verilog.sh"
else
    echo "⚠️  Environment incomplete for VHDL→Verilog: install GHDL with synthesis."
    echo "Run: ./scripts/install_neorv32_verilog.sh"
fi
