#!/bin/bash
# Local environment setup for Rocket Chip tools (regenerated by install_rocket_chip.sh)

# Set JAVA_HOME if not already set (no `local` here — this file may be sourced from scripts using set -e)
if [[ -z "${JAVA_HOME:-}" ]] && command -v java >/dev/null 2>&1; then
    _java_exe="$(command -v java)"
    export JAVA_HOME="$(readlink -f "$_java_exe" 2>/dev/null | sed 's:/bin/java::')"
    unset -v _java_exe
fi

# Prefer JDK from JAVA_HOME on PATH (avoids java 1.8 earlier on PATH)
if [[ -n "${JAVA_HOME:-}" && -x "${JAVA_HOME}/bin/java" ]]; then
    export PATH="${JAVA_HOME}/bin:${PATH}"
fi

# Optional user bin: append so a stray ~/bin/java cannot shadow the JDK
[[ -d "$HOME/bin" ]] && export PATH="$PATH:$HOME/bin"

# Add local Scala to PATH if it exists
if [[ -d "$HOME/.local/share/rocket-chip-tools/scala/scala-2.13.12" ]]; then
    export PATH="$HOME/.local/share/rocket-chip-tools/scala/scala-2.13.12/bin:$PATH"
fi

# Add local SBT to PATH if it exists
if [[ -f "$HOME/.local/share/rocket-chip-tools/sbt/sbt" ]]; then
    export PATH="$HOME/.local/share/rocket-chip-tools/sbt:$PATH"
fi

echo "Local Rocket Chip environment activated"
echo "JAVA_HOME: ${JAVA_HOME:-<unset>}"
echo "PATH includes: $HOME/.local/share/rocket-chip-tools (scala, sbt, ...)"

# Activate Python virtual environment if it exists
if [[ -d "$HOME/.local/share/rocket-chip-tools/venv" ]]; then
    export PATH="$HOME/.local/share/rocket-chip-tools/venv/bin:$PATH"
    # shellcheck source=/dev/null
    source "$HOME/.local/share/rocket-chip-tools/venv/bin/activate"
    echo "Python virtual environment activated: $HOME/.local/share/rocket-chip-tools/venv"
fi
