project: pulpissimo
config_name: pulpissimo_snapshot
generation_date_utc: 2026-08-11 06:17:09
git_commit_short: bfc3d9a1
source_snapshot: /home/yongfu/proj/score/datasets/pulpissimo/bfc3d9a1/source_snapshot
