core_type: network_variants
config_name: xbar_SPARC_2x2
x_tiles: 2
y_tiles: 2
total_tiles: 4
simulator: vlt
generation_date: Wed Apr 15 09:25:29 PM +08 2026
rtl_only: true
description: "OpenPiton network_variants configuration with 2x2 tiles"
